# -*- coding: utf-8 -*-
"""ai-powered paraphrasing tool

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zWsT7xn_sgwSW-QbpWUlm07_mJ-8s7S1

# AI-powered paraphrasing tool
"""

from huggingface_hub import login
login("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")

!pip install transformers sentencepiece torch
!pip install language-tool-python
!pip install nltk rouge-score sentence-transformers

# ================================
# AI PARAPHRASING TOOL
# ================================

# Install dependencies
!pip -q install transformers sentencepiece torch
!pip -q install language-tool-python nltk rouge-score sentence-transformers ipywidgets

# Imports
import torch
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM
import language_tool_python
import nltk
from rouge_score import rouge_scorer
from sentence_transformers import SentenceTransformer, util
from IPython.display import display
import ipywidgets as widgets

# Fix NLTK
nltk.download('punkt')
nltk.download('punkt_tab')

# -----------------------------
# LOAD MODELS (BETTER MODEL)
# -----------------------------
print("Loading models...")

model_name = "humarin/chatgpt_paraphraser_on_T5_base"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSeq2SeqLM.from_pretrained(model_name)

tool = language_tool_python.LanguageTool('en-US')
sim_model = SentenceTransformer('all-MiniLM-L6-v2')

print("Models loaded successfully!\n")

# -----------------------------
# INPUT BOX
# -----------------------------
text_input = widgets.Text(
    value='',
    placeholder='Type your sentence here',
    description='Input:',
    layout=widgets.Layout(width='80%')
)

display(text_input)

# -----------------------------
# FUNCTIONS
# -----------------------------

def paraphrase_text(text):
    input_text = "paraphrase: " + text + " </s>"

    encoding = tokenizer(
        input_text,
        padding=True,
        truncation=True,
        return_tensors="pt"
    )

    outputs = model.generate(
        input_ids=encoding["input_ids"],
        attention_mask=encoding["attention_mask"],
        max_length=128,
        do_sample=True,
        top_k=100,
        top_p=0.95,
        temperature=1.2,      #  more variation
        num_return_sequences=3  #
    )

    return [tokenizer.decode(o, skip_special_tokens=True) for o in outputs]


def correct_grammar(text):
    matches = tool.check(text)
    return language_tool_python.utils.correct(text, matches)


def evaluate_text(original, paraphrased):
    reference = [nltk.word_tokenize(original)]
    candidate = nltk.word_tokenize(paraphrased)
    bleu = nltk.translate.bleu_score.sentence_bleu(reference, candidate)

    scorer = rouge_scorer.RougeScorer(['rouge1', 'rougeL'], use_stemmer=True)
    rouge_scores = scorer.score(original, paraphrased)

    emb1 = sim_model.encode(original, convert_to_tensor=True)
    emb2 = sim_model.encode(paraphrased, convert_to_tensor=True)
    similarity = util.cos_sim(emb1, emb2).item()

    return {
        "BLEU": round(bleu, 4),
        "ROUGE-1": round(rouge_scores['rouge1'].fmeasure, 4),
        "ROUGE-L": round(rouge_scores['rougeL'].fmeasure, 4),
        "Semantic Similarity": round(similarity, 4)
    }

# -----------------------------
# BUTTON
# -----------------------------
button = widgets.Button(description="Paraphrase")
output = widgets.Output()

def on_click(b):
    with output:
        output.clear_output()

        text = text_input.value.strip()

        if not text:
            print("⚠️ Please enter some text.")
            return

        print("Original Text:\n", text)

        # Generate multiple paraphrases
        paraphrases = paraphrase_text(text)

        print("\nParaphrase Options:")
        for i, p in enumerate(paraphrases):
            print(f"{i+1}. {p}")

        # Choose first as final (you can improve later)
        final = correct_grammar(paraphrases[0])

        print("\nFinal Selected Output:\n", final)

        # Evaluation
        scores = evaluate_text(text, final)

        print("\nEvaluation Metrics:")
        for k, v in scores.items():
            print(f"{k}: {v}")

button.on_click(on_click)

display(button, output)